### ISSUE TITLE
I keep getting "Class not found" errors

### ISSUE THREAD

**Issue by the-user-123456** [enjoping/DXFighter#2] opened 2019-01-11 20:09 UTC
First of all - I love this! It would do everything I need, as soon as I get it working. I tried to, but this is what I get:

Fatal error: Class 'DXFighter\lib\Section' not found in C:\Projects\wamp\www\cad2dxf\includes\DXFighter\DXFighter.php on line 79

I started including the classes one by one and then started getting errors like:
Fatal error: Class 'DXFighter\lib\BasicObject' not found in C:\Projects\wamp\www\cad2dxf\includes\DXFighter\lib\SystemVariable.php on line 21

So the included files also throw the same errors. Is this a path issue?

Thanks in advance!

**Comment by enjoping** [comment] 2019-01-17 18:42
Hey,
thanks for your interest in DXFighter and the nice words. I hope we will get the software working on your system. I tried to reproduce the problems but wasn't able on my Mac. I've asked a colleague to do the same on his Windows system but sadly he could not reproduce it either. Therefore I need you to provide me some more information.
Please send me the PHP version which you are using to run DXFighter and if you have an executable version of php to be run in a terminal, please execute `php -d display_errors=on example.php` inside of your copy of the DXFighter repository to run the example script.

**Comment by enjoping** [comment] 2019-08-17 13:54
Closing this issue due to missing information.

**Closed by enjoping** 2019-08-17 13:54 UTC

**Comment by dd701116** [comment] 2019-12-03 12:45
@enjoping  He put his script out of the DXFighter directory.
I had the same problem.
